### ISSUE TITLE
使用hardhat脚本部署合约时，返回invalid BigNumber string但实际部署成功

### ISSUE THREAD

**Issue by nicolegys** [neo-ngd/neo-go#7]
![1681984923684](https://user-images.githubusercontent.com/43694095/233333246-21c8a4d1-709f-4192-b8b4-c456f491b01b.png)

**Comment by ZhangTao1596** [comment]
Fixed f7281aa3d2863ad75bf5398ca7eef026654de8d3
Please retest.

**Comment by nicolegys** [comment]
pass, newbee
