### ISSUE TITLE
使用metamask连续发多笔交易导致节点报错

### ISSUE THREAD

**Issue by nicolegys** [neo-ngd/neo-go#9]
复现步骤：
在服务器启动一个外部节点，metamask连接该外部节点，使用metamask连着发多个交易，到最新的某笔时会突然报eth_getTransactionReceipt错误，过阵子就开始报blockchain: already exists。
p1为log信息，p2为节点控制台信息

![c6c1c986fc78c290b043a570fec3d3a](https://user-images.githubusercontent.com/43694095/233968262-a88dd2a1-d35a-42ab-9544-b11db3fbc59c.png)

![1682331531565](https://user-images.githubusercontent.com/43694095/233968869-d181ac68-3472-400d-b11d-d3f0365ed844.png)

**Comment by ZhangTao1596** [comment]
Fixed a208c3e967d0e685756de3ab3e75d9b85934b7f0
